defaults:
    - override hydra/launcher: submitit_local

# 环境
task: tracking              # 任务名, 'tracking' 表示低层策略，否则为任务名
num_clips: all              # number of training clips to use, or 'all' for all 836 clips
clip_ids: ???               # list of clip ids to use; is set automatically based on num_clips
obs: ???                    # observation type, one of ('state', 'rgb'); is set automatically based on task

# 评估
checkpoint: ???             # 模型检查点的路径 (str)
eval_episodes: 20           # 评估的轮次数 (int)
eval_freq: 50000            # evaluation frequency during training (int)

# 层次
low_level_fp: /path/to/ckpt # 低层次跟踪检查点的路径 (str)
action_scale: 0.3           # scale of high-level actions (float)

# 训练
steps: 10_000_000           # 训练的步数 (int)
batch_size: 256             # 批次大小 (int)
reward_coef: 0.1            # reward loss coefficient (float)
value_coef: 0.1             # value loss coefficient (float)
terminated_coef: 0.1        # termination loss coefficient (float)
consistency_coef: 20        # consistency loss coefficient (float)
rho: 0.5                    # temporal weight for tdmpc2 loss (float)
lr: 3e-4                    # 学习率 (float)
enc_lr_scale: 0.3           # encoder learning rate scale (float)
grad_clip_norm: 20          # gradient clipping norm (float)
tau: 0.01                   # target network ema coefficient (float)
discount: 0.97              # 折扣因子 (float)
buffer_size: 1_000_000      # replay buffer size (int)
exp_name: default           # experiment identifier/name (str)
data_dir: /path/to/data     # path to mocapact dataset (str)

# 规划
mpc: true                   # 是否使用 模型预测控制(model, predictive control, mpc) 或 policy prior (bool)
iterations: 6               # 模型预测控制迭代的次数 (int)
num_samples: 512            # 每次迭代的样本数 (int)
num_elites: 64              # 精英(elites)样本的数目 (int)
num_pi_trajs: 24            # number of policy prior trajectories (int)
horizon: 3                  # 模型预测控制的 规划 步数 (int)
min_std: 0.05               # 模型预测控制采样的最小标准差 (float)
max_std: 2                  # 模型预测控制采样的最大标准差 (float)
temperature: 0.5            # 模型预测控制采样的温度 (float)。温度系数temperature对应的是模型输出的多样性

# policy prior
log_std_min: -10            # minimum log std for policy prior (float)
log_std_max: 2              # maximum log std for policy prior (float)
entropy_coef: 1e-4          # entropy loss coefficient for policy prior (float)

# critic
num_bins: 101               # number of bins for discrete regression (int)
vmin: -10                   # minimum log value for critic (float)
vmax: +10                   # maximum log value for critic (float)

# 架构
num_enc_layers: 2           # 编码器(encoder)层的数目 (int)
enc_dim: 256                # 编码器 隐藏层 维度 (int)
num_channels: 32            # 卷积编码器的通道数 (int)
mlp_dim: 512                # 多层感知机（multilayer perceptron, mlp）隐藏层维度 (int)
latent_dim: 512             # 隐藏状态的维度 (int)
num_q: 5                    # 总体(ensemble) Q 函数的数目 (int)
dropout: 0.01               # 丢弃 Q函数的比率 (float)
simnorm_dim: 8              # simnorm group dimension (int)

# 日志
wandb_project: locomotion          # wandb project name (str)
wandb_entity: openhutb           # wandb entity name (str)
wandb_silent: false         # whether to silence wandb prints (bool)
use_wandb: true             # whether to use wandb (bool)
save_csv: false             # whether to save csv logs (bool)

# 杂项
save_video: true            # 是否保存评估视频 (bool)
save_agent: true            # 是否保存代理的检查点 (bool)
save_freq: 500_000          # 代理检查点的保存频率 (int)
seed: 1                     # 随机种子 (int)

# convenience
work_dir: ???
task_title: ???
obs_shape: ???
action_dim: ???
episode_length: ???
seed_steps: ???
bin_size: ???
