
name: Compile Latex

on: [push]
    
jobs:
  build_latex:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile document with latex 2025
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: sn
          root_file: sn-article.tex
          texlive_version: 2020
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: locomotion.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
